trigger:
  branches:
    include:
      #- main
      - next
  #paths: # Commented out while the majority of the work is updating the pipeline
  #  include:
  #    - *.tf

pr:
  branches:
    include:
      - main
      - next
  #paths:
  #  include:
  #    - *.tf

pool:
  name: Azure Pipelines

resources:
  repositories:
    - repository: build_templates
      type: github
      name: geoffreybaldry/build_templates
      endpoint: geoffreybaldry # The name of the github service connection
      #ref: refs/heads/next

variables:
- group: "terraform-pipeline-vg"
- name: terraform.version
  value: "latest"
  readonly: true

stages:
  - stage: validate_plan
    jobs:
      - job: terraform_validate
        steps:
          - template: init.yml@build_templates
            parameters:
              version: $(terraform.version)
          
          - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV2@2
            displayName: 'Terraform : validate'
            inputs:
              provider: aws
              command: validate
              backendServiceAWS: 'AWS for Terraform Service Connection'

      - job: terraform_plan
        depends_on: terraform_validate
        steps:
          - template: init.yml@build_templates
            parameters:
              version: $(terraform.version)

          - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV2@2
            displayName: 'Terraform : plan'
            inputs:
              provider: aws
              command: plan
              environmentServiceNameAWS: 'AWS for Terraform Service Connection'
