trigger:
  - main
  - next

pool:
  name: Azure Pipelines

resources:
  repositories:
    - repository: build_templates
      type: github
      name: geoffreybaldry/build_templates
      endpoint: geoffreybaldry # The name of the github service connection
      #ref: refs/heads/next

#stages:
#  - stage: aws
#    jobs:
#      - job: terraform_validate
#        #dependsOn: terraform_install
steps:
  - template: init.yml@build_templates
  
  - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV2@2
    displayName: 'Terraform : validate'
    inputs:
      provider: aws
      command: validate
      backendServiceAWS: 'AWS for Terraform Service Connection'

  - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV2@2
    displayName: 'Terraform : plan'
    inputs:
      provider: aws
      command: plan
      environmentServiceNameAWS: 'AWS for Terraform Service Connection'
