# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- next

#pool:
#  vmImage: ubuntu-latest

pool:
  name: Azure Pipelines

stages:
  - stage: terraform_setup
    jobs:
      - job: terraform_install
        steps:
          - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
            displayName: 'Terraform : install latest' 
            inputs:
              terraformVersion: latest

      - job: terraform_init
        dependsOn: terraform_install
        steps:
          - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV2@2
            displayName: 'Terraform : init'
            inputs:
              provider: aws
              backendServiceAWS: 'AWS for Terraform Service Connection'
              backendAWSBucketName: 'jazzygeoff-terraform-state'
              backendAWSKey: terraform.tfstate

      - job: terraform_validate
        dependsOn: terraform_init
        steps:
          - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV2@2
            displayName: 'Terraform : validate'
            inputs:
              provider: aws
              command: validate

#steps:
#- script: echo Hello, world!
#  displayName: 'Run a one-line script'

#- script: |
#    echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
#  displayName: 'Run a multi-line script'
